server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:file:./data/user-db;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true

jwt:
  secret: DeRUCCI-IoT-Platform-JWT-Secret-Key-2026
  whitelist:
    - /api/auth/**
    - /h2-console/**
