server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:file:./data/user-db;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
