server:
  port: 8084

spring:
  application:
    name: device-service
  datasource:
    url: jdbc:h2:file:./data/device-db;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

jwt:
  secret: DeRUCCI-IoT-Platform-JWT-Secret-Key-2026
  whitelist:
    - /api/auth/**
    - /h2-console/**
