server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/products/**
        - id: thing-model-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/thing-models/**
        - id: device-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/devices/**
        - id: ota-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/ota/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
